version: "3"
services:
  # app:
  #   build:
  #     context: ../../
  #     dockerfile: ./docker/object_detection_demo/Dockerfile.local
  #   image: objection_detection_demo_app:latest
  #   container_name: objection_detection_demo_app_local
  #   volumes:
  #     - "../../configs:/home/app/configs"
  #     - "../../src:/home/app/src"
  #   restart: "no"
  #   command: python3 /home/app/src/main.py
  #   ports:
  #     - "8080:5000"

  inference:
    image: openvino/model_server:2023.2
    container_name: objection_detection_demo_inference_local
    volumes:
      - "../../machine_learning/models:/models"
    # restart: "no"
    # expose:
    #   - "9000"
    ports:
      - "9000:9000"
    command: "--model_name 'handguns' --model_path '/models/handguns'  --port '9000' --layout 'NCHW:NCHW' --shape 'auto' --log_level DEBUG"
